### ISSUE TITLE
How to define multiple units in scales like font-size

### ISSUE THREAD

**Issue by jesusbotella** [signal-noise/stylelint-scales#45]
> Clearly describe the documentation issue

Documentation does not specify how to define multiple units for a scale like `font-size`, because example configuration throws invalid option error:
```js
Invalid Option: Invalid option "{"scale":[1,1.5],"units":["px","rem"]}" for rule scales/font-size
```

Secondary options only allow to define one unit in `unit` property, but `font-size` docs show that multiple unit validation is possible.

> What solution would you like to see?

Not sure, though. I guess that a whole rule definition within the documentation like:
```js
"scales/font-size": [[1, 1.5, 2], { unit: "rem" }],
```

**Comment by jeddy3** [comment]
It looks like the documentation doesn't correspond to how the primary option currently works. However, I think the documentation reflects how the primary option _should_ work, i.e. explicit units rather than checking all `<length>` values. 

I'll rustle up a pull request with a non-breaking change to add support for explicit units.
